export {default as Home} from './Home'
export {default as Sign} from './Sign'
export {default as Gym} from './Gym'
export {default as Private} from './Private'
export {default as PrivateRoute} from './PrivateRoute'
